---
hide_body: false
fields:
- type: field_group
  label: Headings
  name: headings
  fields:
  - type: number
    name: font-size
    label: font-size
    config:
      required: true
  - type: select
    name: font-family
    config:
      source:
        type: simple
      required: true
    label: font-family
