---
pages:
- aerospace.md
hide_body: false
fields:
- type: field_group
  name: typography
  label: Typography
  fields:
  - type: field_group
    name: headings
    label: Headings
    fields:
    - type: field_group_list
      name: heading
      label: Heading
      fields:
      - type: text
        name: heading_name
        label: Heading Name
        config:
          required: true
      - type: text
        name: font_family
        label: Font Family
        default: Open Sans
      - type: number
        name: font_size
        label: Font Size
        description: Use 'px' units
        default: '16'
      - type: text
        name: font_weight
        label: Font Weight
        default: normal
      - type: text
        name: color
        label: Color
        description: Use HEX code
        default: "#000"
      - type: text
        name: letter_spacing
        label: Letter Spacing
      - type: text
        name: notes
        label: Notes
      config:
        labelField: heading_name
  - type: field_group
    name: type
    label: Type
    fields:
    - type: field_group_list
      name: element
      label: Element
      fields:
      - type: text
        name: element_name
        label: Element Name
      - type: text
        name: font_family
        label: Font Family
        default: Georgia
      - type: number
        name: font_size
        label: Font Size
        description: Use 'px' units
        default: '18'
      - type: text
        name: font_weight
        label: Font Weight
        default: normal
      - type: text
        name: color
        label: Color
        description: Use HEX code
        default: "#000"
      - type: text
        name: line_height
        label: Line Height
        default: '1.5'
      - type: text
        name: margins
        label: Margins
        description: 'Separate with commas in order: Top, Right, Bottom, Left'
      - type: text
        name: padding
        label: Padding
        description: 'Separate with commas in order: Top, Right, Bottom, Left'
      - type: field_group_list
        name: Borders
        fields:
        - type: select
          name: position
          config:
            source:
              type: simple
            options:
            - Top
            - Right
            - Left
            - Bottom
            - All
          label: Position
          default: Top
        - type: text
          name: color
          label: Color
        - type: number
          name: weight
          label: Weight
      - type: textarea
        name: extra_css
        label: Extra CSS
- type: field_group
  name: colors
  label: Colors
  fields:
  - type: field_group
    name: primary_colors
    label: Primary Colors
    fields:
    - type: field_group_list
      name: color
      label: Color
      fields:
      - type: text
        name: hex_code
        label: Hex code
      config:
        labelField: hex_code
  - type: field_group
    name: secondary_colors
    label: Secondary Colors
    fields:
    - type: field_group_list
      label: Color
      name: color
      fields:
      - type: text
        name: hex_code
        label: Hex code
      config:
        labelField: hex_code
  - type: field_group_list
    label: Interactive Palettes
    name: interactive_palettes
    fields:
    - type: text
      name: palette_name
      label: Palette Name
    - type: field_group_list
      name: colors
      label: Colors
      fields:
      - type: text
        name: color
        label: Color
        description: Use HEX codes
    config:
      labelField: palette_name
- type: field_group_list
  name: links
  label: Links
  fields:
  - type: text
    name: group_name
    label: Group Name
    default: Body Links
  - type: text
    name: description
    label: Description
    default: Default links in the post body
  - type: field_group_list
    name: link
    label: Link
    fields:
    - type: field_group
      label: Base
      name: base
      fields:
      - type: text
        name: font-family
        label: Font Family
        default: Roboto
      - type: number
        name: font-size
        label: Font Size
        description: Use 'px' units
        default: '18'
      - type: text
        name: font-weight
        label: Font Weight
        default: normal
      - type: text
        name: color
        label: Color
        description: Use HEX code
        default: "#000"
      - type: text
        name: text-decoration
        label: Text Decoration
      - type: text
        name: background
        label: Background
        description: 'Use background shorthand: background-color background-image
          background-repeat background-position. (ex: #fff linear-gradient(#fff 50%, #B5BDC1 50%)
          repeat-x 0 100%) '
      - type: text
        name: background-size
        label: Background Size
      - type: textarea
        name: extra_css
        label: Extra CSS
        default: ''
    - type: field_group
      label: Hover
      name: hover
      fields:
      - type: text
        name: font-family
        label: Font Family
        default: Roboto
      - type: number
        name: font-size
        label: Font Size
        description: Use 'px' units
        default: '18'
      - type: text
        name: font-weight
        label: Font Weight
        default: normal
      - type: text
        name: color
        label: Color
        description: Use HEX code
        default: "#000"
      - type: text
        name: text-decoration
        label: Text Decoration
      - type: text
        name: background
        label: Background
        description: 'Use background shorthand: background-color background-image
          background-repeat background-position. (ex: #fff linear-gradient(#fff 50%, #B5BDC1 50%)
          repeat-x 0 100%) '
      - type: text
        name: background-size
        label: Background Size
      - type: textarea
        name: extra_css
        label: Extra CSS
        default: ''
    - type: field_group
      label: Visited
      name: visited
      fields:
      - type: text
        name: font-family
        label: Font Family
        default: Roboto
      - type: number
        name: font-size
        label: Font Size
        description: Use 'px' units
        default: '18'
      - type: text
        name: font-weight
        label: Font Weight
        default: normal
      - type: text
        name: color
        label: Color
        description: Use HEX code
        default: "#000"
      - type: text
        name: text-decoration
        label: Text Decoration
      - type: text
        name: background
        label: Background
        description: 'Use background shorthand: background-color background-image
          background-repeat background-position. (ex: #fff linear-gradient(#fff 50%, #B5BDC1 50%)
          repeat-x 0 100%) '
      - type: text
        name: background-size
        label: Background Size
      - type: textarea
        name: extra_css
        label: Extra CSS
        default: ''
  config:
    labelField: group_name
- type: field_group_list
  name: buttons
  label: Buttons
  fields:
  - type: text
    name: group_name
    label: Group Name
  - type: text
    name: description
    label: Description
  - type: field_group_list
    name: button
    label: Button
    fields:
    - type: field_group
      label: Base
      name: base
      fields:
      - type: text
        name: font-family
        label: Font Family
        default: Georgia
      - type: number
        name: font-size
        label: Font Size
        description: Use 'px' units
        default: '18'
      - type: text
        name: font-weight
        label: Font Weight
        default: normal
      - type: text
        name: line-height
        label: Line Height
        default: '1.5'
      - type: text
        name: letter-spacing
        label: Letter Spacing
        default: normal
      - type: select
        name: text-align
        config:
          source:
            type: simple
          options:
          - Left
          - Right
          - Center
        label: Text Align
        default: Center
      - type: text
        name: color
        label: Color
        description: Use HEX code
        default: "#000"
      - type: text
        name: background-color
        label: Background Color
        description: Use HEX code
      - type: text
        name: padding
        label: Padding
        description: 'Padding shorthand: top right bottom left'
      - type: text
        name: border-top
        label: Top Border
        description: 'Please use border shorthand: border-width border-style border-color.
          (ex: 1px solid #4CB5B9)'
      - type: text
        name: border-right
        label: Right Border
        description: 'Please use border shorthand: border-width border-style border-color.
          (ex: 1px solid #4CB5B9)'
      - type: text
        name: border-bottom
        label: Bottom Border
        description: 'Please use border shorthand: border-width border-style border-color.
          (ex: 1px solid #4CB5B9)'
      - type: text
        name: border-left
        label: Left Border
        description: 'Please use border shorthand: border-width border-style border-color.
          (ex: 1px solid #4CB5B9)'
      - type: textarea
        name: extra_css
        label: Extra CSS
    - type: field_group
      name: hover
      label: Hover
      fields:
      - type: text
        name: font-family
        label: Font Family
        default: Georgia
      - type: number
        name: font-size
        label: Font Size
        description: Use 'px' units
        default: '18'
      - type: text
        name: font-weight
        label: Font Weight
        default: normal
      - type: text
        name: line-height
        label: Line Height
        default: '1.5'
      - type: text
        name: letter-spacing
        label: Letter Spacing
        default: normal
      - type: select
        name: text-align
        config:
          source:
            type: simple
          options:
          - Left
          - Right
          - Center
        label: Text Align
        default: Center
      - type: text
        name: color
        label: Color
        description: Use HEX code
        default: "#000"
      - type: text
        name: background-color
        label: Background Color
        description: Use HEX code
      - type: text
        name: padding
        label: Padding
        description: 'Padding shorthand: top right bottom left'
      - type: text
        name: border-top
        label: Top Border
        description: 'Please use border shorthand: border-width border-style border-color.
          (ex: 1px solid #4CB5B9)'
      - type: text
        name: border-right
        label: Right Border
        description: 'Please use border shorthand: border-width border-style border-color.
          (ex: 1px solid #4CB5B9)'
      - type: text
        name: border-bottom
        label: Bottom Border
        description: 'Please use border shorthand: border-width border-style border-color.
          (ex: 1px solid #4CB5B9)'
      - type: text
        name: border-left
        label: Left Border
        description: 'Please use border shorthand: border-width border-style border-color.
          (ex: 1px solid #4CB5B9)'
      - type: textarea
        name: extra_css
        label: Extra CSS
- type: field_group_list
  name: logos
  label: Logos
  fields:
  - type: text
    name: logo_name
    label: Logo Name
  - type: text
    name: logo_description
    label: Logo Description
  - type: file
    name: upload_logo
    label: Upload logo
  - type: boolean
    name: background_color
    label: Dark Background
  - type: text
    name: height
    label: Height
    description: For stylesheet only
  - type: text
    name: width
    label: Width
    description: For stylesheet only
- type: field_group_list
  name: tables
  label: Tables
  fields:
  - type: text
    name: table_name
    label: Table Name
  - type: text
    name: table_description
    label: Table Description
  - type: file
    label: Image
    name: image
  config:
    labelField: table_name
- type: field_group_list
  name: form_elements
  label: Form Elements
  fields:
  - type: text
    name: form_element_name
    label: Form Element Name
  - type: text
    name: form_element_description
    label: Form Element Description
  - type: file
    name: image
    label: Image
  config:
    labelField: form_element_name
