---
label: Project
hide_body: true
is_partial: false
fields:
- type: select
  config:
    source:
      type: simple
      section: pages
    options:
    - page
    - project
    required: true
  hidden: true
  default: page
  label: Layout
  name: layout
- type: text
  name: program_partners
  label: Program Partners
- type: field_group
  name: initial_styles
  label: Initial Styles
  description: Only for use during project development
  hidden: false
  fields:
  - type: boolean
    name: show_this_section
    label: Show this section
    default: false
  - type: include
    name: initial_styles
    label: Initial Styles
    template: initial-styles
- type: field_group
  name: typography
  label: Typography
  fields:
  - type: text
    label: Import Fonts
    name: import_fonts
    description: Use standard HTML embed layout
  - type: field_group_list
    name: fonts
    label: Fonts
    fields:
    - type: text
      name: name
      label: Name
    - type: text
      name: notes
      label: Notes
    - type: text
      name: css_input
      label: CSS input
    - type: text
      name: link_to_homepage
      label: Link to homepage
  - type: field_group_list
    name: headings
    label: Headings
    fields:
    - type: text
      name: heading_name
      label: Heading Name
    - type: text
      name: font-family
      label: Font Family
      default: Roboto
    - type: text
      name: font-size
      label: Font Size
    - type: text
      name: font-weight
      label: Font Weight
    - type: text
      name: text-transform
      label: Text Transform
      default: normal
    - type: text
      name: color
      label: Color
      description: Use HEX code
      default: "#000"
    - type: text
      name: letter-spacing
      label: Letter Spacing
    - type: text
      name: notes
      label: Notes
    config:
      labelField: heading_name
  - type: field_group_list
    name: elements
    label: Elements
    fields:
    - type: text
      name: element_name
      label: Element Name
    - type: textarea
      default: ''
      name: html_text
      label: HTML text
      config:
        wysiwyg: true
    - type: textarea
      label: Notes
      name: notes
    - type: boolean
      name: body_text
      label: Is this is body text?
    - type: text
      name: font-family
      label: Font Family
      default: Georgia
    - type: text
      name: font-size
      label: Font Size
    - type: text
      name: font-weight
      label: Font Weight
      default: normal
    - type: text
      name: color
      label: Color
      description: Use HEX code
      default: "#000"
    - type: text
      name: line-height
      label: Line Height
      default: '1.5'
    - type: text
      name: margins
      label: Margins
      description: 'Separate with commas in order: Top, Right, Bottom, Left'
    - type: text
      name: padding
      label: Padding
      description: 'Separate with commas in order: Top, Right, Bottom, Left'
    - type: text
      name: border-top
      label: Top Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: text
      name: border-right
      label: Right Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: text
      name: border-bottom
      label: Bottom Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: text
      name: border-left
      label: Left Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: textarea
      name: extra_css
      label: Extra CSS
    config:
      labelField: element_name
- type: field_group
  name: colors
  label: Colors
  fields:
  - type: field_group_list
    name: primary_colors
    label: Primary Colors
    fields:
    - type: text
      name: hex_code
      label: Hex code
    config:
      labelField: hex_code
  - type: field_group_list
    label: Secondary Colors
    name: secondary_color
    fields:
    - type: text
      name: hex_code
      label: Hex code
    config:
      labelField: hex_code
  - type: field_group_list
    label: Interactive Palettes
    name: interactive_palettes
    fields:
    - type: text
      name: palette_name
      label: Palette Name
    - type: field_group_list
      name: colors
      label: Colors
      fields:
      - type: text
        name: hex_code
        label: Hex Code
        description: Use HEX codes
    config:
      labelField: palette_name
- type: field_group_list
  name: links
  label: Links
  fields:
  - type: text
    name: base
    label: Base CSS
  - type: text
    name: hover
    label: Hover CSS
  - type: text
    name: visited
    label: Visited CSS
  config:
    labelField: group_name
- type: field_group_list
  name: buttons
  label: Buttons
  fields:
  - type: text
    name: group_name
    label: Group Name
  - type: text
    name: description
    label: Description
  - type: field_group
    label: Base
    name: base
    fields:
    - type: text
      name: font-family
      label: Font Family
      default: Georgia
    - type: text
      name: font-size
      label: Font Size
      description: Use 'px' units
      default: '18'
    - type: text
      name: font-weight
      label: Font Weight
      default: normal
    - type: text
      name: line-height
      label: Line Height
      default: '1.5'
    - type: text
      name: letter-spacing
      label: Letter Spacing
      default: normal
    - type: text
      name: text-transform
      label: Text Transform
    - type: select
      name: text-align
      config:
        source:
          type: simple
        options:
        - Left
        - Right
        - Center
      label: Text Align
      default: Center
    - type: text
      name: color
      label: Color
      description: Use HEX code
      default: "#000"
    - type: text
      name: background-color
      label: Background Color
      description: Use HEX code
    - type: text
      name: padding
      label: Padding
      description: 'Padding shorthand: top right bottom left'
    - type: text
      name: border-top
      label: Top Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: text
      name: border-right
      label: Right Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: text
      name: border-bottom
      label: Bottom Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: text
      name: border-left
      label: Left Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: textarea
      name: extra_css
      label: Extra CSS
  - type: field_group
    name: hover
    label: Hover
    fields:
    - type: text
      name: font-family
      label: Font Family
      default: Georgia
    - type: text
      name: font-size
      label: Font Size
      description: Use 'px' units
      default: '18'
    - type: text
      name: font-weight
      label: Font Weight
      default: normal
    - type: text
      name: line-height
      label: Line Height
      default: '1.5'
    - type: text
      name: letter-spacing
      label: Letter Spacing
      default: normal
    - type: text
      name: text-transform
      label: Text Transform
    - type: select
      name: text-align
      config:
        source:
          type: simple
        options:
        - Left
        - Right
        - Center
      label: Text Align
      default: Center
    - type: text
      name: color
      label: Color
      description: Use HEX code
      default: "#000"
    - type: text
      name: background-color
      label: Background Color
      description: Use HEX code
    - type: text
      name: padding
      label: Padding
      description: 'Padding shorthand: top right bottom left'
    - type: text
      name: border-top
      label: Top Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: text
      name: border-right
      label: Right Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: text
      name: border-bottom
      label: Bottom Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: text
      name: border-left
      label: Left Border
      description: 'Please use border shorthand: border-width border-style border-color.
        (ex: 1px solid #4CB5B9)'
    - type: textarea
      name: extra_css
      label: Extra CSS
- type: field_group_list
  name: logos
  label: Logos
  fields:
  - type: text
    name: logo_name
    label: Logo Name
  - type: text
    name: logo_description
    label: Logo Description
  - type: file
    name: upload_logo
    label: 'Upload Logo: SVG'
  - type: file
    label: 'Upload Logo: PNG'
    name: upload_logo__png
  - type: file
    name: dark_background
    label: 'Optional Dark Background: SVG'
    description: Include a version of the logo with a dark background
  - type: file
    label: 'Optional Dark Background: PNG'
    name: dark_background__png
  - type: text
    name: bg-color
    label: Background Color for Dark Backgrounds
    description: For stylesheet only.
  - type: text
    name: height
    label: Height
    description: For stylesheet only
  - type: text
    name: width
    label: Width
    description: For stylesheet only
- type: field_group_list
  name: tables
  label: Tables
  fields:
  - type: text
    name: element_name
    label: Table Name
  - type: text
    name: element_description
    label: Table Description
  - type: file
    label: Image
    name: image
  - type: text
    name: height
    label: height
    default: 300px
  config:
    labelField: element_name
- type: field_group_list
  name: form_elements
  label: Form Elements
  fields:
  - type: text
    name: element_name
    label: Form Element Name
  - type: text
    name: element_description
    label: Form Element Description
  - type: text
    name: height
    label: height
    default: 300px
  - type: file
    name: image
    label: Image
  config:
    labelField: element_name
- type: file
  name: screenshot
  label: screenshot
  default: "/uploads/2018/04/23/default browser example.png"
pages:
- on-the-radar.md
- _posts/test.md
- health-commission.md
- stephenson-ocean-security-project.md
- defense-360.md
- beyond-parallel.md
- poni.md
- chinapower.md
- aerospace.md
