---
hide_body: false
fields:
- type: field_group
  label: Headings
  name: headings
  fields:
  - type: field_group
    name: h1
    label: H1
    fields:
    - type: text
      name: color
      label: color
      description: hex codes
      default: "#000"
    - type: select
      name: font-family
      config:
        source:
          type: simple
        options:
        - Expo Serif
        - Museo Sans
        - Georgia
        required: true
      label: Font-Family
      default: Georgia
    - type: number
      name: font_size
      label: Font Size
      description: Use 'px' units
      config:
        required: true
- type: field_group
  name: body_text
  label: Body Text
  fields:
  - type: text
    name: color
    label: Color
    default: "#000"
    description: hex
  - type: select
    config:
      source:
        type: datafiles
    label: Font Family
    name: font_family
