---
pages:
- elements.md
hide_body: false
fields:
- type: field_group
  name: typography
  label: Typography
  fields:
  - type: field_group
    name: headings
    label: Headings
    fields:
    - type: field_group_list
      name: heading
      label: Heading
      fields:
      - type: select
        name: heading_name
        config:
          source:
            type: simple
          options:
          - H1
          - H2
          - H3
          - H4
          - H5
          - H6
        label: Heading Name
      - type: text
        name: font_family
        label: Font Family
        default: Open Sans
      - type: number
        name: font_size
        label: Font Size
        description: Use 'px' units
        default: '16'
      - type: text
        name: font_weight
        label: Font Weight
        default: normal
      - type: text
        name: color
        label: Color
        description: Use HEX code
        default: "#000"
      - type: text
        name: letter_spacing
        label: Letter Spacing
      - type: text
        name: notes
        label: Notes
  - type: field_group
    name: type
    label: Type
    fields:
    - type: field_group_list
      name: element
      label: Element
      fields:
      - type: text
        name: element_name
        label: Element Name
      - type: text
        name: font_family
        label: Font Family
        default: Georgia
      - type: number
        name: font_size
        label: Font Size
        description: Use 'px' units
        default: '18'
      - type: text
        name: font_weight
        label: Font Weight
        default: normal
      - type: text
        name: color
        label: Color
        description: Use HEX code
        default: "#000"
      - type: text
        name: line_height
        label: Line Height
        default: '1.5'
      - type: text
        name: margins
        label: Margins
        description: 'Separate with commas in order: Top, Right, Bottom, Left'
      - type: text
        name: padding
        label: Padding
        description: 'Separate with commas in order: Top, Right, Bottom, Left'
      - type: field_group_list
        name: Borders
        fields:
        - type: select
          name: position
          config:
            source:
              type: simple
            options:
            - Top
            - Right
            - Left
            - Bottom
            - All
          label: Position
          default: Top
        - type: text
          name: color
          label: Color
        - type: number
          name: weight
          label: Weight
      - type: textarea
        name: extra_css
        label: Extra CSS
- type: field_group
  name: colors
  label: Colors
  fields:
  - type: field_group
    name: primary_colors
    label: Primary Colors
    fields:
    - type: field_group_list
      name: color
      label: Color
      fields:
      - type: text
        name: hex_code
        label: Hex code
      config:
        labelField: hex_code
  - type: field_group
    name: secondary_colors
    label: Secondary Colors
    fields:
    - type: field_group_list
      label: Color
      name: color
      fields:
      - type: text
        name: hex_code
        label: Hex code
      config:
        labelField: hex_code
  - type: field_group
    name: interactive_pallettes
    label: Interactive Palettes
    fields:
    - type: field_group_list
      fields:
      - type: text
        name: palette_name
        label: Palette Name
        config:
          required: true
      - type: field_group_list
        name: colors
        label: Colors
        fields:
        - type: text
          name: color
          label: Color
          description: Use HEX codes
          config:
            required: true
      label: Palette Group
      name: palette_group
      config:
        labelField: palette_name
